version: '3'
services:
  db:
    image: postgres:11.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/docker-compose
    depends_on:
      - db
  nginx: 
      image: nginx:1.15.2
      volumes: 
        - /usr/local/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      volumes: 
        - /usr/local/etc/nginx/conf.d:/etc/nginx/conf.d
      ports:
        - "3000:3000"
      